export * from './burger.icon'
export * from './x.icon'
export * from './table'
export * from './back.icon'
export * from './company-logo.icon'
export * from './delete.icon'
export * from './pencil.icon'
